// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderSvc.proto

package com.meric.order.model;

public interface OrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.meric.order.model.OrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string orderDetails = 1;</code>
   */
  java.lang.String getOrderDetails();
  /**
   * <code>string orderDetails = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderDetailsBytes();
}
