// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderSvc.proto

package com.meric.order.model;

public interface OrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.meric.order.model.OrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string orderNo = 1;</code>
   */
  java.lang.String getOrderNo();
  /**
   * <code>string orderNo = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderNoBytes();

  /**
   * <code>string orderDate = 2;</code>
   */
  java.lang.String getOrderDate();
  /**
   * <code>string orderDate = 2;</code>
   */
  com.google.protobuf.ByteString
      getOrderDateBytes();
}
