// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderSvc.proto

package com.meric.order.model;

public final class OrderSvc {
  private OrderSvc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_meric_order_model_OrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_meric_order_model_OrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_meric_order_model_OrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_meric_order_model_OrderResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016OrderSvc.proto\022\025com.meric.order.model\"" +
      "2\n\014OrderRequest\022\017\n\007orderNo\030\001 \001(\t\022\021\n\torde" +
      "rDate\030\002 \001(\t\"%\n\rOrderResponse\022\024\n\014orderDet" +
      "ails\030\001 \001(\t2h\n\022CreateOrderService\022R\n\005orde" +
      "r\022#.com.meric.order.model.OrderRequest\032$" +
      ".com.meric.order.model.OrderResponseB\002P\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_meric_order_model_OrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_meric_order_model_OrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_meric_order_model_OrderRequest_descriptor,
        new java.lang.String[] { "OrderNo", "OrderDate", });
    internal_static_com_meric_order_model_OrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_meric_order_model_OrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_meric_order_model_OrderResponse_descriptor,
        new java.lang.String[] { "OrderDetails", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
